### ISSUE TITLE
Investigate options for backing up DynamoDB

### ISSUE THREAD

**Issue by fillup** [silinternational/serverless-mfa-api#28]
Amazon provides a module for continuous backup using a bunch of AWS services to automate it all, but it looks quite complicated. We should research it first and then decide if something like a simple dump and backup to s3 would be sufficient. 

https://github.com/awslabs/dynamodb-continuous-backup

**Comment by forevermatt** [comment]
This is now being done using [shevchenkos/DynamoDbBackUp](https://github.com/shevchenkos/DynamoDbBackUp). See the "[Automated Backups" section of the README](https://github.com/silinternational/serverless-mfa-api#automated-backups) for details.
